### ISSUE TITLE
Tau fruit will not grow to a Saturated Tau.

### ISSUE THREAD

**Issue by hammydude2001** [SmashingModsTogether/SMT-Issues#9] opened 2021-11-08 08:04 UTC
**Describe the issue**
Tau fruit don't seem to be growing correctly.

**To Reproduce**
1. Go to a tilled piece of dirt and place tau fruit on it, with water and mobs nearby.
2. wait for it to grow...
3. It does not grow, I saw it get to 14 percent but stopped. 

**Expected behavior**
I expected the tau fruit to continue growing leeching life from the cows/chickens around it. I also tried putting it next to a skeleton spawner for more mobs. This is what the in game blood magic book told me would happen. 

**Screenshots**

**Game Environment(please complete the following information):**
- Windows 10
- Java Version
- modpack version 1.0.3 lite. 
- no clue what mod causes the issue but the issue is under the blood magic mod. 

**Additional context**
I am not certain this is a bug honestly, I may not be doing something correctly. But with that said I did a lot of research about this tau fruit growing into a saturated Tau and found no explanations or videos for it. This is something that stops me from getting a blood altar tier 4 so it is a little annoying. If I am doing something wrong and anyone can tell me how to grow this tau fruit it would be much appreciated.

**Comment by Dark-Arcana** [comment] 2021-11-08 19:01
Blood Magic for 1.16 is still pretty new. A lot of features haven't been implemented at all or completely yet, even if they are referenced in the book. I will take a look into this to see if it should be working or not and make sure it does if it is implemented. But it might not be.

Thanks for reporting in either case.

**Comment by Dark-Arcana** [comment] 2021-11-11 02:28
Timbro tested this and confirms that there isn't a bug. Basically, it's working as intended, takes forever to grow, and has some wonky mechanics. I'll be closing this issue now then.

**Closed by Dark-Arcana** 2021-11-11 02:28 UTC
Labels: bug
