### ISSUE TITLE
Attacking a trident summons lightning

### ISSUE THREAD

**Issue by Timbroglio** [SmashingModsTogether/SMT-Issues#34] opened 2022-02-02 20:11 UTC
**Describe the issue**
Using a trident in melee causes about a dozen lightning strikes instantly, even without the enchantment to have it summon lightning

**To Reproduce**
1. Get trident
2. Stab a mob with it
3. Sudden massive explosion of lightning and fire

**Expected behavior**
Mob takes damage from the trident

**Screenshots**
![image](https://user-images.githubusercontent.com/15707879/152229679-9eac9179-aaf8-4002-abe3-d50d776b25e6.png)

**Comment by Dark-Arcana** [comment] 2022-02-02 22:49
Is it a bug or a feature? :thonk:

**Comment by HolyPoseida** [comment] 2022-02-08 00:31
It’s certainly a bug. It effectively ruined my favorite weapon in the game. I was so happy when I finally got my trident cause I love tridents, but when I discovered I can’t kill mobs with it in melee (because it sets fire to the ground and so the mob drops get BURNED) I was honestly pretty devastated. From then on, it just became a meme weapon to troll friends by summoning lightning on them.

**Comment by Dark-Arcana** [comment] 2022-02-08 00:37
Awe I'm sorry it ruined your favorite weapon. Ok so this is something we will have to figure out. It's hard sometimes though to see what causes issues like this.

**Comment by OldManDorn** [comment] 2022-02-08 02:35
I will say that not only does it happen from a trident that was created, but it also happens from a dropped trident. Holy crafted theirs, I got mine as a drop from a mob. both of them bring fire and lightning.
Hope that helps.

**Comment by Dark-Arcana** [comment] 2022-02-09 01:55
I narrowed the issue down to ArmorPlus and just need to investigate how to fix it.

**Comment by Dark-Arcana** [comment] 2022-02-09 21:37
Confirmed fixed in next update.

**Closed as completed by Dark-Arcana** 2022-02-09 21:37 UTC
Labels: bug
