### ISSUE TITLE
Clicking OAuth on Server Screen Crashes Game

### ISSUE THREAD

**Issue by SavageKiller13** [SmashingModsTogether/SMT-Issues#27] opened 2021-11-27 19:31 UTC
Trying to play on a server I go into the multiplayer screen and try to play on a server. Clicking on the server gives the restart launcher screen. Try to use OAuth to reauthenticate client to play on server. Clicking on OAuth button instantly crashes the game.

1. Go to Multiplayer Screen
2. Click on OAuth Button
3. Game instantly crashes

The Expected behavior is to have the OAuth screen to ReAuth the client.

- Operating System Windows 10 build 19042
- Java Version OpenJDK 16.0.1
- Modpack Version 1.1.2-lite (hotfix version)
- Mod causing issue if applicable OAuth 1.1.1-1.16

[crash-2021-11-27_12.20.02-client.txt](https://github.com/SmashingModsTogether/SMT-Issues/files/7612304/crash-2021-11-27_12.20.02-client.txt)

latest.log file. Includes only related crash information
https://gist.github.com/SavageKiller13/8c83f49a5bccac6e705e866278239945

**Comment by Dark-Arcana** [comment] 2021-11-29 22:55
This is very weird! Based on the crash report you provided and the one I got from testing, there is a null pointer exception when rendering an entity in the world. However, there is no entity to load as there is no world loaded. Basically, there is some issue with the Toro Health bars rendering on some entity when you click on the OAuth login button. I will do more investigating and then cross-reference this to both mod's github issues.

Edit: I haven't used this mod since I originally tested that it does in fact work. I forgot that it renders a player entity to the screen on the OAuth login screen. So there is an incompatibility there. The mod developer did just fix an issue with the Hats mod, so they might be receptive to fixing this issue or providing a configuration option to disable rendering the player entity.

**Comment by Dark-Arcana** [comment] 2021-11-29 23:04
My crash report is ever so slightly different. So I'll provide that here for additional context:
https://gist.github.com/Dark-Arcana/bf4eadc299c134265847fd15842b1f5c

**Comment by Dark-Arcana** [comment] 2021-12-01 03:13
Confirmed fixed in the next update!

**Closed as completed by Dark-Arcana** 2021-12-01 03:13 UTC
Labels: bug
